modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL=""
logoFile="logo.png"
license="MIT"
[[mods]]
modId="autoticfish"
version="0.0.1"
displayName="AutoFish for Tic"
authors="Creeping Creeper"
description='''
An addon mod for Tinkers' Construct.
    '''
  displayURL="https://www.curseforge.com/minecraft/mc-mods/autoticfish"

[[dependencies.autoticfish]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.autoticfish]]
modId="forge"
mandatory=true
versionRange="[47.1.40,)"
ordering="NONE"
side="BOTH"

[[dependencies.autoticfish]]
modId="tconstruct"
mandatory=true
versionRange="[3.10.2.143,)"
ordering = "AFTER"
side="BOTH"

[[dependencies.autoticfish]]
modId="forgeautofish"
mandatory=true
versionRange="[6.0.0,)"
ordering = "AFTER"
side="BOTH"